using System.Globalization;
using System.Reflection;
using System.Security.Cryptography;
using OCGForge.Ignis.Gameplay;
using OCGForge.Ignis.Model;

namespace OCGForge.Ignis.Model.Tests;

internal static class I6EModelInputTests
{
    private const string NativeVocabularyCanonicalHex =
        "000000216f6367666f7267652e6d6f64656c5f636172645f766f636162756c6172792e7631" +
        "000000216f6367666f7267652e6d6f64656c5f636172645f766f636162756c6172792e7631" +
        "00000027617363656e64696e675f7075626c69635f70617373636f64655f72616e6b5f706c75735f74776f" +
        "00000003000003e9000007d200000bbb";

    private const string NativeVocabularyIdentity =
        "model_card_vocabulary.v1.1b5a874ad1e7ab88864238b7ea1b088ce2afacde908bb55169e934f90624dbd5";

    // Emitted by native OCGForge model sources at f929de0b. These values are
    // not generated by the Ignis implementation.
    private const int NativeComposedEncodedLength = 706;
    private const string NativeComposedEncodedSha256 =
        "b5dd7c860454e727f4dfed029e6cb8642607fbdf46152e6f6688bc72bf1c3ccf";

    private const string NativeComposedEncodedHex =
        "0000001f6f6367666f7267652e6d6f64656c5f656e636f6465645f696e7075742e76310000001f6f6367666f7267652e6d6f64656c5f656e636f6465645f696e7075742e76310000001f6f6367666f7267652e6d6f64656c5f6c6f676963616c5f696e7075742e7631000000596d6f64656c5f636172645f766f636162756c6172792e76312e3537326666326133363834316665383633386633373534333231616564663864393434336239646335356137633639396632326630633832366636636332396200000040353733366335323637626664613237353563656166636462303363356562323733346435643338386166333065316233363337653361323135303130343230360000000000000000000000000001000e01000000000000000000000000000000000200001f4000001f4001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000100000040346633663065643961396664333532383433366162363834616434646165333730633362313565656162346139396362313362343839383831336131666266330000000100090101000000000000000000000000000000000100000001000000e77075626c69635f616374696f6e2e76312e30303030303032323666363336373636366637323637363532653730373536323663363936333566363136333734363936663665356636393634363536653734363937343739326537363331303030303030323236663633363736363666373236373635326537303735363236633639363335663631363337343639366636653566363936343635366537343639373437393265373633313030303030303036373936353733356636653666303130313030303030303030303030303030303030303030303030303030303030303030303030303030";
    private const string NativeComposedIdentity =
        "model_input.v1.c25c19f7e6cb7d608b3849a8499937dcc8a6198cd57b8bfe5e1a1ccd874a4483";

    private const string NativeComposedLogicalHexNative =
        "0000001f6f6367666f7267652e6d6f64656c5f6c6f676963616c5f696e7075742e76310000001f6f6367666f7267652e6d6f64656c5f6c6f676963616c5f696e7075742e7631000000403537333663353236376266646132373535636561666364623033633565623237333464356433383861663330653162333633376533613231353031303432303600000000000000000001000000067965735f6e6f01000000000000000000000000970000001d6f6367666f7267652e7075626c69635f736166655f73746174652e76310000001d6f6367666f7267652e7075626c69635f736166655f73746174652e763100000000000000000000000200001f4000001f40010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000001000000067965735f6e6f000000e77075626c69635f616374696f6e2e76312e3030303030303232366636333637363636663732363736353265373037353632366336393633356636313633373436393666366535663639363436353665373436393734373932653736333130303030303032323666363336373636366637323637363532653730373536323663363936333566363136333734363936663665356636393634363536653734363937343739326537363331303030303030303637393635373335663665366630313031303030303030303030303030303030303030303030303030303030303030303030303030303001010000000000000000000000000000000000000001010000004034663366306564396139666433353238343336616236383461643464616533373063336231356565616234613939636231336234383938383133613166626633";

    private const string NativePickLogicalHex =
        "0000001f6f6367666f7267652e6d6f64656c5f6c6f676963616c5f696e7075742e76310000001f6f6367666f7267652e6d6f64656c5f6c6f676963616c5f696e7075742e76310000004036366566393030393736383832353834663163383933356539386332373138313738383733326436303435303964323366326238653236366662623230353934000000000000000000010000000e636172645f73656c656374696f6e01000000000000000000000000970000001d6f6367666f7267652e7075626c69635f736166655f73746174652e76310000001d6f6367666f7267652e7075626c69635f736166655f73746174652e763100000000000000000000000200001f4000001f40010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000001000000047069636b000000df7075626c69635f616374696f6e2e76312e30303030303032323666363336373636366637323637363532653730373536323663363936333566363136333734363936663665356636393634363536653734363937343739326537363331303030303030323236663633363736363666373236373635326537303735363236633639363335663631363337343639366636653566363936343635366537343639373437393265373633313030303030303034373036393633366230303030303030303030303130303030303030303030303030303030303437303639363336620000000000010000000000000000047069636b00010000004064306233313834626636366530656631313034333230626135663239663132383033393963346437646261653239633263363161363066626466636363626666";
    private const string NativePickIdentity =
        "model_input.v1.b3a9e9320d970a5c55f1a13193dd9bbe895b70daca902eea1b6df48685f04955";
    private const int NativePickEncodedLength = 692;
    private const string NativePickEncodedSha256 =
        "59666ac15cb2260bf5c1799f9cbfa6c96fe025cc33b36130c1412319226a7287";

    private const string NativeFinishLogicalHex =
        "0000001f6f6367666f7267652e6d6f64656c5f6c6f676963616c5f696e7075742e76310000001f6f6367666f7267652e6d6f64656c5f6c6f676963616c5f696e7075742e76310000004036366566393030393736383832353834663163383933356539386332373138313738383733326436303435303964323366326238653236366662623230353934000000000000000000010000000e636172645f73656c656374696f6e01000000000000000000000000970000001d6f6367666f7267652e7075626c69635f736166655f73746174652e76310000001d6f6367666f7267652e7075626c69635f736166655f73746174652e763100000000000000000000000200001f4000001f400100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000010000000666696e697368000000df7075626c69635f616374696f6e2e76312e3030303030303232366636333637363636663732363736353265373037353632366336393633356636313633373436393666366535663639363436353665373436393734373932653736333130303030303032323666363336373636366637323637363532653730373536323663363936333566363136333734363936663665356636393634363536653734363937343739326537363331303030303030303636363639366536393733363830303030303030303030303030303030303030303036363636393665363937333638000000000000000000000666696e69736801010000004038386232313730393332383064336631363730333961363566393638633836616661383563346432653635306466643632316363336466633331633635643962";
    private const string NativeFinishIdentity =
        "model_input.v1.9b3a185bc7a8738f77a68f672807202647222792ad46fc9fa0082ddd3a3a8208";
    private const int NativeFinishEncodedLength = 688;
    private const string NativeFinishEncodedSha256 =
        "e6b540909df99804d20fd827ed218f3434fe8abd419188cd072f98b109a1b30d";
    private const int NativeRichLogicalLength = 1495;
    private const string NativeRichLogicalSha256 =
        "a7dbb5f49ecfa82801577e46f11b0bb8e127300ecd56284e387c5e2e6e900339";
    private const int NativeRichEncodedLength = 1347;
    private const string NativeRichEncodedSha256 =
        "250420d14c2216b5de590851a6448a5064a5efc547d78c08d29eb2a8c7c47a10";
    private const string NativeRichIdentity =
        "model_input.v1.3f0c69655739af835e74f24fa5bf542bbc802decb8333dd1810c5d5c8ec5daa2";

    public static void TestLogicalEncodedVocabularyBridge()
    {
        TestNullInputsFailClosed();
        TestVocabularyNativeKatAndImmutability();
        TestComposedPlayerToActNativeKat();
        TestContinuationNativeKats();
        TestFullAcceptedBoundaryBridge();
        TestCandidateNToNAndRouting();
        TestOptionalPresenceAndHistoricalReferences();
        TestMissingKnownPasscodeFailsClosed();
        TestDetachedAndMalformedInputsFailClosed();
        TestPairedPublicWorlds();
    }

    private static void TestNullInputsFailClosed()
    {
        OcgForgeLogicalModelInputResultV1 logical =
            OcgForgeLogicalModelInputBridgeV1.TryCreate(null, null);
        Require(!logical.IsSuccess && logical.Value is null,
            "null accepted I6B/I6D inputs must fail closed");
        OcgForgeCardVocabularyResultV1 vocabulary =
            OcgForgeCardVocabularyV1.TryCreate(null);
        Require(!vocabulary.IsSuccess && vocabulary.Value is null,
            "null vocabulary must fail closed");
    }

    private static void TestVocabularyNativeKatAndImmutability()
    {
        uint[] source = { 1001, 2002, 3003 };
        OcgForgeCardVocabularyResultV1 result =
            OcgForgeCardVocabularyV1.TryCreate(source);
        Require(result.IsSuccess && result.Value is not null,
            "native vocabulary vector was rejected");
        OcgForgeCardVocabularyV1 vocabulary = result.Value!;
        Require(Convert.ToHexString(vocabulary.CanonicalBytes).ToLowerInvariant() ==
                NativeVocabularyCanonicalHex &&
                vocabulary.Identity == NativeVocabularyIdentity,
            "vocabulary differs from the independent native KAT");
        Require(OcgForgeCardVocabularyV1.PadId == 0 &&
                OcgForgeCardVocabularyV1.UnknownOrRedactedId == 1 &&
                vocabulary.IdForPublicPasscode(1001) == 2 &&
                vocabulary.IdForPublicPasscode(3003) == 4 &&
                vocabulary.IdForPublicPasscode(9999) is null,
            "vocabulary reserved or ranked IDs are incorrect");
        source[0] = 9999;
        Require(vocabulary.AscendingPasscodes[0] == 1001,
            "vocabulary did not deep-copy its source");
        foreach (uint[] invalid in new[]
                 {
                     new uint[] { 0 },
                     new uint[] { 2002, 1001 },
                     new uint[] { 1001, 1001 }
                 })
        {
            OcgForgeCardVocabularyResultV1 rejected =
                OcgForgeCardVocabularyV1.TryCreate(invalid);
            Require(!rejected.IsSuccess && rejected.Value is null &&
                    rejected.Error?.Code ==
                        OcgForgeCardVocabularyErrorCodeV1.InvalidPasscodeList,
                "invalid vocabulary was repaired instead of rejected");
        }
    }

    private static void TestComposedPlayerToActNativeKat()
    {
        OcgForgeLogicalModelInputV1 logical = RequireLogical(
            CreateAcceptedDecision(
                CreateMinimalFrame(),
                CreateYesNoContext(),
                new[]
                {
                    New<FlatYesNoPublicCandidateDescriptorV1>(
                        "native-yes",
                        FlatPromptChoiceKindV1.No)
                }));
        Require(logical.PublicSafeState.Globals.PlayerToAct == 0,
            "I6D player_to_act was not composed into the logical safe state");
        Require(Convert.ToHexString(logical.CanonicalBytes).ToLowerInvariant() ==
                NativeComposedLogicalHexNative,
            "composed logical player_to_act bytes differ from native KAT");
        OcgForgeCardVocabularyV1 vocabulary =
            OcgForgeCardVocabularyV1.TryCreate(Array.Empty<uint>()).Value!;
        OcgForgeEncodedModelInputV1 encoded =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(logical, vocabulary).Value!;
        byte[] encodedBytes = encoded.CanonicalBytes;
        Require(encodedBytes.Length == NativeComposedEncodedLength &&
                Convert.ToHexString(encodedBytes).ToLowerInvariant() ==
                    NativeComposedEncodedHex &&
                Convert.ToHexString(SHA256.HashData(encodedBytes)).ToLowerInvariant() ==
                    NativeComposedEncodedSha256 &&
                OcgForgeModelInputIdentityV1.Create(logical, encoded, vocabulary) ==
                    NativeComposedIdentity,
            "composed encoded or identity bytes differ from native KAT");
        byte[] identityBytes =
            OcgForgeModelInputIdentityV1.CanonicalModelInputIdentityBytes(
                logical,
                encoded);
        Require(Convert.ToHexString(SHA256.HashData(identityBytes)).ToLowerInvariant() ==
                NativeComposedIdentity["model_input.v1.".Length..],
            "composed model-input identity bytes do not hash to native KAT");
    }

    private static void TestContinuationNativeKats()
    {
        PerspectiveSafeFrameV1 frame = CreateMinimalFrame();
        FlatPromptCardSelectionPublicContextV1 context =
            New<FlatPromptCardSelectionPublicContextV1>((byte)0, 1U, 2U, false);
        OcgForgePublicDecisionContextV1 pickDecision =
            CreateAcceptedDecision(frame, context, new[]
            {
                New<FlatPromptCardSelectionAnonymousCandidateV1>(
                    "native-pick",
                    0)
            });
        Require(!pickDecision.Candidates[0].SubmitsEngineResponse,
            "I6D did not carry intermediate transition metadata");
        OcgForgeLogicalModelInputV1 pick = RequireLogical(pickDecision);
        OcgForgeCardVocabularyV1 vocabulary =
            OcgForgeCardVocabularyV1.TryCreate(Array.Empty<uint>()).Value!;
        OcgForgeEncodedModelInputV1 pickEncoded =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(pick, vocabulary).Value!;
        Require(Convert.ToHexString(pick.CanonicalBytes).ToLowerInvariant() ==
                NativePickLogicalHex &&
                pickEncoded.CanonicalBytes.Length == NativePickEncodedLength &&
                Convert.ToHexString(SHA256.HashData(pickEncoded.CanonicalBytes))
                    .ToLowerInvariant() == NativePickEncodedSha256 &&
                OcgForgeModelInputIdentityV1.Create(pick, pickEncoded, vocabulary) ==
                    NativePickIdentity &&
                !pick.CandidateFeatures[0].SubmitsEngineResponse,
            "intermediate continuation differs from native P5 KAT");

        OcgForgePublicDecisionContextV1 finishDecision =
            CreateAcceptedDecision(frame, context, new[]
            {
                New<FlatPromptFinishPublicCandidateV1>("native-finish")
            });
        Require(finishDecision.Candidates[0].SubmitsEngineResponse,
            "I6D did not carry terminal transition metadata");
        OcgForgeLogicalModelInputV1 finish = RequireLogical(finishDecision);
        OcgForgeEncodedModelInputV1 finishEncoded =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(finish, vocabulary).Value!;
        Require(Convert.ToHexString(finish.CanonicalBytes).ToLowerInvariant() ==
                NativeFinishLogicalHex &&
                finishEncoded.CanonicalBytes.Length == NativeFinishEncodedLength &&
                Convert.ToHexString(SHA256.HashData(finishEncoded.CanonicalBytes))
                    .ToLowerInvariant() == NativeFinishEncodedSha256 &&
                OcgForgeModelInputIdentityV1.Create(finish, finishEncoded, vocabulary) ==
                    NativeFinishIdentity &&
                finish.CandidateFeatures[0].SubmitsEngineResponse,
            "terminal continuation differs from native P5 KAT");

        FlatPromptCounterSourcePublicDescriptorV1 counterSource =
            New<FlatPromptCounterSourcePublicDescriptorV1>(
                0,
                (ushort)3,
                Locator("p0:MONSTER_ZONE:0"));
        OcgForgePublicDecisionContextV1 amountDecision =
            CreateAcceptedDecision(
                CreateRichFrame(),
                New<FlatPromptCounterSelectionPublicContextV1>(
                    (byte)0,
                    (ushort)5,
                    (ushort)3,
                    new[] { counterSource }),
                new[]
                {
                    New<FlatPromptCounterAmountPublicCandidateV1>(
                        "native-amount",
                        0,
                        2)
                });
        Require(!amountDecision.Candidates[0].SubmitsEngineResponse &&
                RequireLogical(amountDecision).CandidateFeatures[0]
                    .ContinuationOperation == "amount",
            "I6D amount continuation was not classified as intermediate");

        OcgForgePublicDecisionContextV1 cancelDecision =
            CreateAcceptedDecision(
                CreateRichFrame(),
                context,
                new[] { New<FlatPromptCancelPublicCandidateV1>("native-cancel") });
        Require(cancelDecision.Candidates[0].SubmitsEngineResponse &&
                RequireLogical(cancelDecision).CandidateFeatures[0]
                    .ContinuationOperation == "cancel",
            "I6D cancel continuation was not classified as terminal");

        FlatPromptSortSourcePublicDescriptorBaseV1 sortSource =
            New<FlatPromptSortSourceLocatorPublicDescriptorV1>(
                0,
                Locator("p0:MONSTER_ZONE:0"));
        OcgForgePublicDecisionContextV1 bypassDecision =
            CreateAcceptedDecision(
                CreateRichFrame(),
                New<FlatPromptSortSelectionPublicContextV1>(
                    (byte)0,
                    FlatPromptSortKindV1.SortCard,
                    new[] { sortSource }),
                new[] { New<FlatPromptCancelPublicCandidateV1>("native-bypass") });
        Require(bypassDecision.Candidates[0].SubmitsEngineResponse &&
                RequireLogical(bypassDecision).CandidateFeatures[0]
                    .ContinuationOperation == "bypass",
            "I6D bypass continuation was not classified as terminal");
    }

    private static void TestFullAcceptedBoundaryBridge()
    {
        PerspectiveSafeFrameV1 frame = CreateRichFrame();
        OcgForgePublicDecisionContextV1 decision = CreateAcceptedDecision(
            frame,
            CreateChainContext(),
            new[]
            {
                New<FlatChainPublicCandidateDescriptorV1>(
                    "local.chain",
                    0,
                    Locator("p0:MONSTER_ZONE:0"),
                    42UL,
                    (byte)0)
            });
        OcgForgeLogicalModelInputV1 logical = RequireLogical(decision);
        Require(logical.SchemaIdValue == OcgForgeLogicalModelInputV1.SchemaId &&
                logical.PerspectivePlayer == 0 &&
                logical.DecisionIndex == 0 &&
                logical.PublicObservationContextKind == "chain" &&
                logical.PublicObservationContextPlayer == 0 &&
                logical.PublicSafeState.Globals.PlayerToAct == 0 &&
                logical.CandidateFeatures.Count == 1 &&
                logical.CandidateRouting.Count == 1 &&
                logical.CandidateRouting[0].PublicActionKey ==
                    decision.Candidates[0].PublicActionKey &&
                logical.PublicLocatorTable.Count >= 3 &&
                logical.ReferencedPublicEntities.Count == 1 &&
                logical.ReferencedPublicEntities[0].Value ==
                    "p0:MONSTER_ZONE:0" &&
                logical.PublicSafeState.Entities.Count == 3 &&
                logical.PublicSafeState.Relationships.Count == 1 &&
                logical.PublicSafeState.Chain.Links.Count == 1 &&
                logical.PublicSafeState.VisibleEvents.Count == 2,
            "logical input lost accepted I6D/state fields");
        Require(logical.PublicSafeState.VisibleEvents[0].Entity is { } historical &&
                historical.Locator.Value == "p0:MONSTER_ZONE:0" &&
                historical.Locator.PublicLocatorOrdinal < logical.PublicLocatorTable.Count,
            "historical reference was not mapped through the locator table");

        OcgForgeCardVocabularyV1 vocabulary =
            OcgForgeCardVocabularyV1.TryCreate(new uint[] { 1001, 2002, 3003 }).Value!;
        OcgForgeEncodedModelInputV1 encoded =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(logical, vocabulary).Value!;
        OcgForgeEncodedEntityV1 monster = encoded.Entities.Single(entity =>
            entity.PublicLocatorOrdinal == logical.PublicSafeState.Entities.Single(source =>
                source.Card.Locator == "p0:MONSTER_ZONE:0").PublicLocatorOrdinal);
        Require(monster.Current is not null &&
                monster.Current.LinkRating == 2 &&
                monster.Current.LinkMarkerCodes.SequenceEqual(new byte[] { 1, 4 }) &&
                monster.Current.Counters.SequenceEqual(
                    new[] { new OcgForgeEncodedCounterV1(7, 3) }) &&
                encoded.Entities.Any(entity => !entity.IdentityKnown &&
                    entity.CardVocabularyId == 1 &&
                    entity.Printed is null && entity.Current is null),
            "encoded Current/vocabulary fields were not preserved");
        OcgForgeModelInputIdentityResultV1 identity =
            OcgForgeModelInputIdentityV1.TryCreate(logical, encoded, vocabulary);
        Require(identity.IsSuccess && identity.Identity is not null &&
                identity.Identity.StartsWith("model_input.v1.", StringComparison.Ordinal),
            identity.FieldPath ?? "model-input identity was rejected");
        byte[] logicalBytes = logical.CanonicalBytes;
        byte[] encodedBytes = encoded.CanonicalBytes;
        Require(logicalBytes.Length == NativeRichLogicalLength &&
                Convert.ToHexString(SHA256.HashData(logicalBytes)).ToLowerInvariant() ==
                    NativeRichLogicalSha256 &&
                encodedBytes.Length == NativeRichEncodedLength &&
                Convert.ToHexString(SHA256.HashData(encodedBytes)).ToLowerInvariant() ==
                    NativeRichEncodedSha256 &&
                identity.Identity == NativeRichIdentity,
            "complex locator/event/relationship vector differs from native KAT");
    }

    private static void TestCandidateNToNAndRouting()
    {
        OcgForgePublicDecisionContextV1 decision = CreateAcceptedDecision(
            CreateRichFrame(),
            New<FlatPromptOptionPublicContextV1>((byte)0),
            new[]
            {
                New<FlatOptionPublicCandidateDescriptorV1>("local.a", 0, 7UL),
                New<FlatOptionPublicCandidateDescriptorV1>("local.b", 1, 7UL),
                New<FlatOptionPublicCandidateDescriptorV1>("local.c", 2, 9UL)
            });
        OcgForgeLogicalModelInputV1 logical = RequireLogical(decision);
        Require(logical.CandidateFeatures.Count == 3 &&
                logical.CandidateRouting.Count == 3 &&
                logical.CandidateFeatures[0].Choice?.ResponseIndex == 0 &&
                logical.CandidateFeatures[1].Choice?.ResponseIndex == 1 &&
                logical.CandidateFeatures[2].Choice?.ResponseIndex == 2 &&
                logical.CandidateRouting[0].PublicActionKey ==
                    decision.Candidates[0].PublicActionKey &&
                logical.CandidateRouting[1].PublicActionKey ==
                    decision.Candidates[1].PublicActionKey &&
                logical.CandidateRouting[2].PublicActionKey ==
                    decision.Candidates[2].PublicActionKey,
            "candidate N-to-N order/routing was changed");
        OcgForgePublicDecisionContextV1 equivalent = CreateAcceptedDecision(
            CreateRichFrame(),
            New<FlatPromptOptionPublicContextV1>((byte)0),
            new[]
            {
                New<FlatOptionPublicCandidateDescriptorV1>("other.a", 0, 7UL),
                New<FlatOptionPublicCandidateDescriptorV1>("other.b", 1, 7UL),
                New<FlatOptionPublicCandidateDescriptorV1>("other.c", 2, 9UL)
            });
        Require(logical.CanonicalBytes.SequenceEqual(RequireLogical(equivalent).CanonicalBytes),
            "Ignis-local candidate keys changed logical bytes");
    }

    private static void TestOptionalPresenceAndHistoricalReferences()
    {
        OcgForgeLogicalModelInputV1 absent = RequireLogical(
            CreateAcceptedDecision(
                CreateRichFrame(null),
                CreateYesNoContext(),
                new[]
                {
                    New<FlatYesNoPublicCandidateDescriptorV1>(
                        "absent",
                        FlatPromptChoiceKindV1.No)
                }));
        OcgForgeLogicalModelInputV1 present = RequireLogical(
            CreateAcceptedDecision(
                CreateRichFrame(0),
                CreateYesNoContext(),
                new[]
                {
                    New<FlatYesNoPublicCandidateDescriptorV1>(
                        "present",
                        FlatPromptChoiceKindV1.No)
                }));
        Require(absent.PublicSafeState.Globals.TurnPlayer is null &&
                present.PublicSafeState.Globals.TurnPlayer == 0 &&
                !absent.CanonicalBytes.SequenceEqual(present.CanonicalBytes),
            "ABSENT and PRESENT(0) collapsed in logical bytes");
        OcgForgeCardVocabularyV1 vocabulary =
            OcgForgeCardVocabularyV1.TryCreate(new uint[] { 1001, 2002, 3003 }).Value!;
        OcgForgeEncodedModelInputV1 absentEncoded =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(absent, vocabulary).Value!;
        OcgForgeEncodedModelInputV1 presentEncoded =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(present, vocabulary).Value!;
        Require(absentEncoded.Globals.TurnPlayer is null &&
                presentEncoded.Globals.TurnPlayer == 0 &&
                !absentEncoded.CanonicalBytes.SequenceEqual(presentEncoded.CanonicalBytes),
            "ABSENT and PRESENT(0) collapsed in encoded bytes");
        Require(absent.PublicSafeState.VisibleEvents[0].Entity is { } eventEntity &&
                eventEntity.Locator.PublicLocatorOrdinal < absent.PublicLocatorTable.Count,
            "historical reference did not use the shared locator table");
        Require(absent.PublicSafeState.Relationships[0].Source
                    .CurrentEntityOrdinal is not null &&
                absent.PublicSafeState.Relationships[0].Source.CurrentEntityOrdinal == 1,
            "current relationship reference did not resolve to the entity ordinal");
    }

    private static void TestMissingKnownPasscodeFailsClosed()
    {
        OcgForgeLogicalModelInputV1 logical = RequireLogical(
            CreateAcceptedDecision(
                CreateRichFrame(),
                CreateYesNoContext(),
                new[]
                {
                    New<FlatYesNoPublicCandidateDescriptorV1>(
                        "missing",
                        FlatPromptChoiceKindV1.No)
                }));
        OcgForgeCardVocabularyV1 vocabulary =
            OcgForgeCardVocabularyV1.TryCreate(new uint[] { 2002, 3003 }).Value!;
        OcgForgeEncodedModelInputResultV1 result =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(logical, vocabulary);
        Require(!result.IsSuccess && result.Value is null &&
                result.Error?.Code ==
                    OcgForgeEncodedModelInputErrorCodeV1.UnknownPublicPasscode,
            "known passcode absent from vocabulary was redacted");
    }

    private static void TestDetachedAndMalformedInputsFailClosed()
    {
        OcgForgeLogicalModelInputV1 logical = RequireLogical(
            CreateAcceptedDecision(
                CreateRichFrame(),
                CreateYesNoContext(),
                new[]
                {
                    New<FlatYesNoPublicCandidateDescriptorV1>(
                        "detached",
                        FlatPromptChoiceKindV1.No)
                }));
        OcgForgeCardVocabularyV1 vocabulary =
            OcgForgeCardVocabularyV1.TryCreate(new uint[] { 1001, 2002, 3003 }).Value!;
        OcgForgeEncodedModelInputV1 encoded =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(logical, vocabulary).Value!;
        OcgForgeCardVocabularyV1 other =
            OcgForgeCardVocabularyV1.TryCreate(new uint[] { 1001, 2002, 4004 }).Value!;
        OcgForgeModelInputIdentityResultV1 detached =
            OcgForgeModelInputIdentityV1.TryCreate(logical, encoded, other);
        Require(!detached.IsSuccess && detached.Identity is null,
            "detached vocabulary was accepted");

        OcgForgeLogicalModelInputV1 malformed = New<OcgForgeLogicalModelInputV1>(
            OcgForgeLogicalModelInputV1.SchemaId,
            new string('0', 64),
            null,
            (byte)0,
            0UL,
            null,
            null,
            Array.Empty<OcgForgeLogicalPublicLocatorV1>(),
            Array.Empty<OcgForgeLogicalPublicLocatorV1>(),
            logical.PublicSafeState,
            Array.Empty<OcgForgeLogicalCandidateRoutingV1>(),
            Array.Empty<OcgForgeLogicalCandidateV1>());
        OcgForgeEncodedModelInputResultV1 rejected =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(malformed, vocabulary);
        Require(!rejected.IsSuccess && rejected.Value is null &&
                rejected.Error?.Code ==
                    OcgForgeEncodedModelInputErrorCodeV1.InvalidLogicalModelInput,
            "malformed logical input was not rejected atomically");
    }

    private static void TestPairedPublicWorlds()
    {
        OcgForgeLogicalModelInputV1 first = RequireLogical(
            CreateAcceptedDecision(
                CreateRichFrame(),
                CreateYesNoContext(),
                new[]
                {
                    New<FlatYesNoPublicCandidateDescriptorV1>(
                        "world-a",
                        FlatPromptChoiceKindV1.Yes)
                }));
        OcgForgeLogicalModelInputV1 second = RequireLogical(
            CreateAcceptedDecision(
                CreateRichFrame(),
                CreateYesNoContext(),
                new[]
                {
                    New<FlatYesNoPublicCandidateDescriptorV1>(
                        "world-b",
                        FlatPromptChoiceKindV1.Yes)
                }));
        OcgForgeCardVocabularyV1 vocabulary =
            OcgForgeCardVocabularyV1.TryCreate(new uint[] { 1001, 2002, 3003 }).Value!;
        OcgForgeEncodedModelInputV1 firstEncoded =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(first, vocabulary).Value!;
        OcgForgeEncodedModelInputV1 secondEncoded =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(second, vocabulary).Value!;
        Require(first.CanonicalBytes.SequenceEqual(second.CanonicalBytes) &&
                firstEncoded.CanonicalBytes.SequenceEqual(secondEncoded.CanonicalBytes) &&
                OcgForgeModelInputIdentityV1.Create(first, firstEncoded, vocabulary) ==
                    OcgForgeModelInputIdentityV1.Create(second, secondEncoded, vocabulary),
            "equal public worlds produced different I6E values");
    }

    private static OcgForgeLogicalModelInputV1 RequireLogical(
        OcgForgePublicDecisionContextV1 decision)
    {
        OcgForgeLogicalModelInputResultV1 result =
            OcgForgeLogicalModelInputBridgeV1.TryCreate(AcceptedBundle(), decision);
        Require(result.IsSuccess && result.Value is not null,
            result.Error?.ToString() ?? "logical input was rejected");
        return result.Value!;
    }

    private static OcgForgeModelContractBundleV1 AcceptedBundle()
    {
        OcgForgeModelContractBundlePreflightResultV1 result =
            OcgForgeModelContractBundleV1.TryAccept(
                I6BBundlePreflightTests.CreateManifest());
        Require(result.IsSuccess && result.Bundle is not null,
            result.Error?.ToString() ?? "I6B bundle was rejected");
        return result.Bundle!;
    }

    private static OcgForgePublicDecisionContextV1 CreateAcceptedDecision(
        PerspectiveSafeFrameV1 frame,
        FlatPromptPublicContextV1 context,
        IReadOnlyList<FlatPublicCandidateDescriptorV1> candidates)
    {
        FlatPromptProjectionResultV1 projection =
            New<FlatPromptProjectionResultV1>(
                true,
                FlatPromptErrorCodeV1.None,
                context,
                candidates);
        OcgForgeAcceptedDecisionBoundaryProducerV1 producer = new();
        Require(producer.TryAccept(
                frame,
                projection,
                out OcgForgeAcceptedDecisionBoundaryV1? boundary,
                out OcgForgeAcceptedDecisionBoundaryProducerErrorV1? error) &&
            boundary is not null,
            error?.ToString() ?? "I6D boundary was rejected");
        OcgForgePublicDecisionContextResultV1 result =
            OcgForgePublicCandidateBridgeV1.TryCreate(boundary);
        Require(result.IsSuccess && result.Context is not null,
            result.Error?.ToString() ?? "I6D context was rejected");
        return result.Context!;
    }

    private static FlatPromptPublicContextV1 CreateChainContext() =>
        New<FlatPromptChainPublicContextV1>((byte)0, (byte)0, false, 0U, 0U);

    private static FlatPromptPublicContextV1 CreateYesNoContext() =>
        New<FlatPromptYesNoPublicContextV1>((byte)0, 42UL);

    private static PerspectiveSafeFrameV1 CreateMinimalFrame()
    {
        PerspectiveSafeFrameSourceResultV1 result =
            PerspectiveSafePublicFrameSourceV1.TryCreate(
                new PerspectiveSafeFrameSourceInputV1(
                    new PerspectiveSafeGlobalsV1(
                        0,
                        new uint[] { 8000, 8000 },
                        playerToAct: null,
                        turnPlayer: null,
                        turnCount: null,
                        phase: null,
                        chainLength: 0,
                        winner: null,
                        winReason: null,
                        terminal: false),
                    Array.Empty<PerspectiveSafeZoneV1>(),
                    Array.Empty<PerspectiveSafeEntityV1>(),
                    Array.Empty<PerspectiveSafeRelationshipV1>(),
                    new PerspectiveSafeChainStateV1(
                        0,
                        Array.Empty<PerspectiveSafeChainLinkV1>()),
                    Array.Empty<PerspectiveSafeVisibleEventV1>(),
                    new PerspectiveSafeMatchContextV1(
                        0,
                        0,
                        new PerspectiveSafeKnowledgeV1(true, false),
                        new PerspectiveSafeDeckV1(false),
                        new PerspectiveSafeDeckV1(false))));
        Require(result.IsSuccess && result.Frame is not null,
            result.Error?.ToString() ?? "minimal frame was rejected");
        return result.Frame!;
    }

    private static PerspectiveSafeFrameV1 CreateRichFrame(byte? turnPlayer = 0)
    {
        PerspectiveSafeCardPropertiesV1 printedMonster = new(
            type: 0x401,
            attribute: 0x20,
            race: 1,
            attack: 2500,
            defense: 2000,
            baseAttack: 2500,
            baseDefense: 2000,
            level: 8,
            linkRating: 2,
            linkMarkers: new[]
            {
                PerspectiveSafeLinkMarkerV1.Bottom,
                PerspectiveSafeLinkMarkerV1.Right
            });
        PerspectiveSafeCardPropertiesV1 currentMonster = new(
            type: 0x401,
            attribute: 0x20,
            race: 1,
            attack: 2700,
            defense: 2100,
            baseAttack: 2500,
            baseDefense: 2000,
            level: 8,
            linkRating: 2,
            linkMarkers: new[]
            {
                PerspectiveSafeLinkMarkerV1.Bottom,
                PerspectiveSafeLinkMarkerV1.Right
            },
            statusFlags: 8,
            counters: new[] { new PerspectiveSafeCounterV1(7, 3) });
        PerspectiveSafeCardPropertiesV1 printedHand = new(
            type: 2,
            attribute: 0x10,
            race: 2,
            level: 4);

        PerspectiveSafeEntityV1[] entities =
        {
            new(
                "p0:HAND:public:2002:0",
                true,
                2002,
                0,
                0,
                PerspectiveSafeSemanticZoneV1.Hand,
                0,
                null,
                PerspectiveSafePositionV1.FaceUpAttack,
                true,
                false,
                printedHand,
                null),
            new(
                "p0:MONSTER_ZONE:0",
                true,
                1001,
                0,
                0,
                PerspectiveSafeSemanticZoneV1.MonsterZone,
                0,
                null,
                PerspectiveSafePositionV1.FaceUpAttack,
                true,
                false,
                printedMonster,
                currentMonster),
            new(
                "p1:SPELL_TRAP_ZONE:0",
                false,
                null,
                1,
                1,
                PerspectiveSafeSemanticZoneV1.SpellTrapZone,
                0,
                null,
                PerspectiveSafePositionV1.FaceDownDefense,
                false,
                true)
        };

        PerspectiveSafeFrameSourceResultV1 result =
            PerspectiveSafePublicFrameSourceV1.TryCreate(
                new PerspectiveSafeFrameSourceInputV1(
                    new PerspectiveSafeGlobalsV1(
                        0x1122334455667788UL,
                        new uint[] { 8000, 7000 },
                        playerToAct: null,
                        turnPlayer: turnPlayer,
                        turnCount: 0,
                        phase: 0,
                        chainLength: 1),
                    new[]
                    {
                        new PerspectiveSafeZoneV1(0, PerspectiveSafeSemanticZoneV1.MainDeck, 40, 0, 40, false),
                        new PerspectiveSafeZoneV1(0, PerspectiveSafeSemanticZoneV1.MonsterZone, 1, 1, 0, true),
                        new PerspectiveSafeZoneV1(1, PerspectiveSafeSemanticZoneV1.MainDeck, 40, 0, 40, false),
                        new PerspectiveSafeZoneV1(1, PerspectiveSafeSemanticZoneV1.SpellTrapZone, 1, 0, 1, false)
                    },
                    entities,
                    new[]
                    {
                        new PerspectiveSafeRelationshipV1(
                            PerspectiveSafeRelationshipKindV1.Target,
                            "p0:MONSTER_ZONE:0",
                            "p0:HAND:public:2002:0")
                    },
                    new PerspectiveSafeChainStateV1(
                        1,
                        new[]
                        {
                            new PerspectiveSafeChainLinkV1(
                                0,
                                0,
                                "p0:MONSTER_ZONE:0",
                                PerspectiveSafeSemanticZoneV1.MonsterZone,
                                0x1020304050607080UL,
                                new[] { "p0:HAND:public:2002:0" })
                        }),
                    new[]
                    {
                        new PerspectiveSafeVisibleEventV1(
                            1,
                            PerspectiveSafeVisibleEventKindV1.CardMoved,
                            0,
                            "p0:MONSTER_ZONE:0",
                            1001,
                            PerspectiveSafeSemanticZoneV1.Hand,
                            PerspectiveSafeSemanticZoneV1.MonsterZone,
                            1,
                            -500,
                            7,
                            0,
                            null,
                            null,
                            0x1020304050607080UL,
                            new[] { "p1:SPELL_TRAP_ZONE:0" }),
                        new PerspectiveSafeVisibleEventV1(
                            2,
                            PerspectiveSafeVisibleEventKindV1.CounterChanged,
                            0,
                            "p0:MONSTER_ZONE:0",
                            null,
                            null,
                            null,
                            3,
                            null,
                            7,
                            0,
                            null,
                            null,
                            null,
                            Array.Empty<string>())
                    },
                    new PerspectiveSafeMatchContextV1(
                        0,
                        0x1122334455667788UL,
                        new PerspectiveSafeKnowledgeV1(true, false),
                        new PerspectiveSafeDeckV1(
                            true,
                            new uint[] { 1001, 2002 },
                            new uint[] { 3003 }),
                        new PerspectiveSafeDeckV1(false))));
        Require(result.IsSuccess && result.Frame is not null,
            result.Error?.ToString() ?? "rich frame was rejected");
        return result.Frame!;
    }

    private static PublicSemanticLocatorV1 Locator(string text)
    {
        Require(PublicSemanticLocatorV1.TryParse(
                text,
                out PublicSemanticLocatorV1? value) && value is not null,
            $"invalid locator {text}");
        return value!;
    }

    private static T New<T>(params object?[] arguments)
        where T : class
    {
        object? value = Activator.CreateInstance(
            typeof(T),
            BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic,
            binder: null,
            args: arguments,
            culture: CultureInfo.InvariantCulture);
        return (T)(value ?? throw new InvalidOperationException(
            $"Could not construct {typeof(T).Name}."));
    }

    private static void Require(bool condition, string message)
    {
        if (!condition)
        {
            throw new InvalidOperationException(message);
        }
    }
}
