using System.Globalization;
using System.Reflection;
using System.Security.Cryptography;
using OCGForge.Ignis.Gameplay;
using OCGForge.Ignis.Model;

namespace OCGForge.Ignis.Model.Tests;

internal static class I6EModelInputTests
{
    private const string NativeVocabularyIdentity =
        "model_card_vocabulary.v1.1b5a874ad1e7ab88864238b7ea1b088ce2afacde908bb55169e934f90624dbd5";

    private const string NativeVocabularyCanonicalHex =
        "000000216f6367666f7267652e6d6f64656c5f636172645f766f636162756c6172792e7631" +
        "000000216f6367666f7267652e6d6f64656c5f636172645f766f636162756c6172792e7631" +
        "00000027617363656e64696e675f7075626c69635f70617373636f64655f72616e6b5f706c75735f74776f" +
        "00000003000003e9000007d200000bbb";

    // These model-input vectors were emitted by a small C++ program linked
    // against the pinned OCGForge model/environment libraries. The model
    // source blobs were verified unchanged between f929de0b and that local
    // build; the expected values are not generated by this C# implementation.
    private const string NativeMinimalLogicalHex =
        "0000001f6f6367666f7267652e6d6f64656c5f6c6f676963616c5f696e7075742e7631" +
        "0000001f6f6367666f7267652e6d6f64656c5f6c6f676963616c5f696e7075742e7631" +
        "0000004037356634646339323566386430316362643132316636383561376637303239643866346138646131636532373161653065386666353561613332306432366536" +
        "00000000000000000001000000067965735f6e6f01000000000000000000000000960000001d6f6367666f7267652e7075626c69635f736166655f73746174652e76310000001d6f6367666f7267652e7075626c69635f736166655f73746174652e763100000000000000000000000200001f4000001f400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000001000000067965735f6e6f000000e77075626c69635f616374696f6e2e76312e3030303030303232366636333637363636663732363736353265373037353632366336393633356636313633373436393666366535663639363436353665373436393734373932653736333130303030303032323666363336373636366637323637363532653730373536323663363936333566363136333734363936663665356636393634363536653734363937343739326537363331303030303030303637393635373335663665366630313031303030303030303030303030303030303030303030303030303030303030303030303030303001010000000000000000000000000000000000000001010000004034663366306564396139666433353238343336616236383461643464616533373063336231356565616234613939636231336234383938383133613166626633";

    private const string NativeMinimalEncodedHex =
        "0000001f6f6367666f7267652e6d6f64656c5f656e636f6465645f696e7075742e76310000001f6f6367666f7267652e6d6f64656c5f656e636f6465645f696e7075742e76310000001f6f6367666f7267652e6d6f64656c5f6c6f676963616c5f696e7075742e7631000000596d6f64656c5f636172645f766f636162756c6172792e76312e3537326666326133363834316665383633386633373534333231616564663864393434336239646335356137633639396632326630633832366636636332396200000040373566346463393235663864303163626431323166363835613766373032396438663461386461316365323731616530653866663535616133323064323665360000000000000000000000000001000e01000000000000000000000000000000000200001f4000001f40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000100000040346633663065643961396664333532383433366162363834616434646165333730633362313565656162346139396362313362343839383831336131666266330000000100090101000000000000000000000000000000000100000001000000e77075626c69635f616374696f6e2e76312e30303030303032323666363336373636366637323637363532653730373536323663363936333566363136333734363936663665356636393634363536653734363937343739326537363331303030303030323236663633363736363666373236373635326537303735363236633639363335663631363337343639366636653566363936343635366537343639373437393265373633313030303030303036373936353733356636653666303130313030303030303030303030303030303030303030303030303030303030303030303030303030";

    private const string NativeMinimalModelInputIdentity =
        "model_input.v1.40bd5568dc78f2ef610abed44d263f7e844a48c75e9cfe126521217242173d1b";

    public static void TestLogicalEncodedVocabularyBridge()
    {
        TestNullInputsFailClosed();
        TestVocabularyNativeKatAndImmutability();
        TestMinimalNativeLogicalEncodedKat();
        TestFullAcceptedBoundaryBridge();
        TestCandidateNToNAndRouting();
        TestContinuationSubmissionMetadata();
        TestOptionalPresenceAndHistoricalReferences();
        TestMissingKnownPasscodeFailsClosed();
        TestDetachedAndMalformedInputsFailClosed();
        TestPairedPublicWorldsAndFreshProcessValues();
    }

    private static void TestNullInputsFailClosed()
    {
        OcgForgeLogicalModelInputResultV1 logical =
            OcgForgeLogicalModelInputBridgeV1.TryCreate(null, null);
        Require(!logical.IsSuccess && logical.Value is null,
            "null accepted I6B/I6D inputs must fail closed");

        OcgForgeCardVocabularyResultV1 vocabulary =
            OcgForgeCardVocabularyV1.TryCreate(null);
        Require(!vocabulary.IsSuccess && vocabulary.Value is null,
            "null vocabulary must fail closed");
    }

    private static void TestVocabularyNativeKatAndImmutability()
    {
        uint[] source = { 1001, 2002, 3003 };
        OcgForgeCardVocabularyResultV1 result =
            OcgForgeCardVocabularyV1.TryCreate(source);
        Require(result.IsSuccess && result.Value is not null,
            result.Error?.ToString() ?? "native vocabulary vector was rejected");

        OcgForgeCardVocabularyV1 vocabulary = result.Value!;
        Require(Convert.ToHexString(vocabulary.CanonicalBytes).ToLowerInvariant() ==
                NativeVocabularyCanonicalHex,
            "vocabulary canonical bytes differ from the independent native KAT");
        Require(vocabulary.Identity == NativeVocabularyIdentity,
            "vocabulary identity differs from the independent native KAT");
        Require(OcgForgeCardVocabularyV1.PadId == 0 &&
                OcgForgeCardVocabularyV1.UnknownOrRedactedId == 1 &&
                vocabulary.IdForPublicPasscode(1001) == 2 &&
                vocabulary.IdForPublicPasscode(3003) == 4 &&
                vocabulary.IdForPublicPasscode(9999) is null,
            "vocabulary reserved or ranked IDs are incorrect");

        source[0] = 9999;
        Require(vocabulary.AscendingPasscodes[0] == 1001,
            "vocabulary did not deep-copy the caller list");

        foreach (uint[] invalid in new[]
                 {
                     new uint[] { 0 },
                     new uint[] { 2002, 1001 },
                     new uint[] { 1001, 1001 }
                 })
        {
            OcgForgeCardVocabularyResultV1 rejected =
                OcgForgeCardVocabularyV1.TryCreate(invalid);
            Require(!rejected.IsSuccess && rejected.Value is null &&
                    rejected.Error?.Code ==
                        OcgForgeCardVocabularyErrorCodeV1.InvalidPasscodeList,
                "invalid vocabulary list was repaired instead of rejected");
        }
    }

    private static void TestMinimalNativeLogicalEncodedKat()
    {
        OcgForgePublicDecisionContextV1 decision =
            CreateAcceptedDecision(
                CreateMinimalFrame(),
                CreateYesNoContext(),
                new[]
                {
                    New<FlatYesNoPublicCandidateDescriptorV1>(
                        "native-minimal",
                        FlatPromptChoiceKindV1.No)
                });
        OcgForgeLogicalModelInputV1 logical = RequireLogical(decision);
        OcgForgeCardVocabularyV1 vocabulary =
            OcgForgeCardVocabularyV1.TryCreate(Array.Empty<uint>()).Value!;
        OcgForgeEncodedModelInputV1 encoded =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(logical, vocabulary).Value!;

        Require(Convert.ToHexString(logical.CanonicalBytes).ToLowerInvariant() ==
                NativeMinimalLogicalHex,
            "logical canonical bytes differ from the pinned native model KAT");
        Require(Convert.ToHexString(encoded.CanonicalBytes).ToLowerInvariant() ==
                NativeMinimalEncodedHex,
            "encoded canonical bytes differ from the pinned native model KAT");
        byte[] identityBytes = OcgForgeModelInputIdentityV1.CanonicalModelInputIdentityBytes(
            logical,
            encoded);
        string identityDigest = Convert.ToHexString(
                SHA256.HashData(identityBytes)).ToLowerInvariant();
        Require(OcgForgeModelInputIdentityV1.Create(logical, encoded, vocabulary) ==
                NativeMinimalModelInputIdentity,
            "model-input identity differs from the pinned native model KAT");
        Require(identityDigest == NativeMinimalModelInputIdentity["model_input.v1.".Length..],
            "model-input identity bytes do not hash to the native KAT");
    }

    private static void TestFullAcceptedBoundaryBridge()
    {
        OcgForgeModelContractBundleV1 bundle = AcceptedBundle();
        OcgForgePublicDecisionContextV1 decision =
            CreateAcceptedDecision(CreateFrame(), CreateChainContext(), new[]
            {
                New<FlatChainPublicCandidateDescriptorV1>(
                    "local.chain",
                    0,
                    Locator("p0:MONSTER_ZONE:0"),
                    42UL,
                    (byte)0)
            });

        OcgForgeLogicalModelInputResultV1 logicalResult =
            OcgForgeLogicalModelInputBridgeV1.TryCreate(bundle, decision);
        Require(logicalResult.IsSuccess && logicalResult.Value is not null,
            logicalResult.Error?.ToString() ?? "accepted I6D boundary was rejected");
        OcgForgeLogicalModelInputV1 logical = logicalResult.Value!;

        Require(logical.SchemaIdValue == OcgForgeLogicalModelInputV1.SchemaId &&
                logical.PerspectivePlayer == 0 && logical.DecisionIndex == 0 &&
                logical.PublicObservationContextKind == "chain" &&
                logical.PublicObservationContextPlayer == 0 &&
                logical.CandidateFeatures.Count == 1 &&
                logical.CandidateRouting.Count == 1 &&
                logical.CandidateRouting[0].PublicActionKey ==
                    decision.Candidates[0].PublicActionKey,
            "logical top-level I6D fields are not bound exactly");
        Require(logical.PublicLocatorTable.Count >= 3 &&
                logical.ReferencedPublicEntities.Count == 1 &&
                logical.ReferencedPublicEntities[0].Value == "p0:MONSTER_ZONE:0" &&
                logical.PublicSafeState.Entities.Count == 3 &&
                logical.PublicSafeState.Relationships.Count == 1 &&
                logical.PublicSafeState.Chain.Links.Count == 1 &&
                logical.PublicSafeState.VisibleEvents.Count == 2,
            "logical safe state or locator table lost accepted public fields");
        Require(logical.PublicSafeState.VisibleEvents[0].Entity is { } eventEntity &&
                eventEntity.Locator.Value == "p0:MONSTER_ZONE:0" &&
                eventEntity.Locator.PublicLocatorOrdinal < logical.PublicLocatorTable.Count,
            "historical event reference did not use the shared locator table");

        OcgForgeCardVocabularyResultV1 vocabularyResult =
            OcgForgeCardVocabularyV1.TryCreate(new uint[] { 1001, 2002, 3003 });
        Require(vocabularyResult.IsSuccess && vocabularyResult.Value is not null,
            "full bridge vocabulary was rejected");
        OcgForgeCardVocabularyV1 vocabulary = vocabularyResult.Value!;
        OcgForgeEncodedModelInputResultV1 encodedResult =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(logical, vocabulary);
        Require(encodedResult.IsSuccess && encodedResult.Value is not null,
            encodedResult.Error?.ToString() ?? "logical input was not encoded");
        OcgForgeEncodedModelInputV1 encoded = encodedResult.Value!;

        Require(encoded.CardVocabularyIdentity == vocabulary.Identity &&
                encoded.Entities.Any(entity => entity.IdentityKnown &&
                    entity.CardVocabularyId == 2) &&
                encoded.Entities.Any(entity => !entity.IdentityKnown &&
                    entity.CardVocabularyId == 1 && entity.Printed is null &&
                    entity.Current is null) &&
                encoded.VisibleEvents[0].PublicCardVocabularyId == 2 &&
                encoded.CandidateFeatures.Count == logical.CandidateFeatures.Count &&
                encoded.RoutingKeys.SequenceEqual(
                    logical.CandidateRouting.Select(value => value.PublicActionKey)),
            "encoded model input did not preserve vocabulary or N-to-N fields");
        OcgForgeEncodedEntityV1 encodedMonster = encoded.Entities.Single(
            entity => entity.PublicLocatorOrdinal == logical.PublicSafeState.Entities
                .Single(source => source.Card.Locator == "p0:MONSTER_ZONE:0")
                .PublicLocatorOrdinal);
        Require(encodedMonster.Current is not null &&
                encodedMonster.Current.LinkRating == 2 &&
                encodedMonster.Current.LinkMarkerCodes.SequenceEqual(new byte[] { 1, 4 }) &&
                encodedMonster.Current.Counters.SequenceEqual(
                    new[] { new OcgForgeEncodedCounterV1(7, 3) }),
            "encoded Current properties were not preserved exactly");

        OcgForgeModelInputIdentityResultV1 identity =
            OcgForgeModelInputIdentityV1.TryCreate(logical, encoded, vocabulary);
        Require(identity.IsSuccess && identity.Identity is not null &&
                identity.Identity.StartsWith("model_input.v1.", StringComparison.Ordinal) &&
                identity.Identity.Length == "model_input.v1.".Length + 64,
            identity.FieldPath ?? "model-input identity was rejected");
        Require(OcgForgeModelInputIdentityV1.CanonicalBytes(logical, encoded).Length >
                logical.CanonicalBytes.Length,
            "model-input identity did not bind both canonical inputs");
    }

    private static void TestCandidateNToNAndRouting()
    {
        PerspectiveSafeFrameV1 frame = CreateFrame();
        OcgForgePublicDecisionContextV1 decision =
            CreateAcceptedDecision(frame, New<FlatPromptOptionPublicContextV1>((byte)0), new[]
            {
                New<FlatOptionPublicCandidateDescriptorV1>("local.a", 0, 7UL),
                New<FlatOptionPublicCandidateDescriptorV1>("local.b", 1, 7UL),
                New<FlatOptionPublicCandidateDescriptorV1>("local.c", 2, 9UL)
            });
        OcgForgeLogicalModelInputResultV1 result =
            OcgForgeLogicalModelInputBridgeV1.TryCreate(AcceptedBundle(), decision);
        Require(result.IsSuccess && result.Value is not null,
            result.Error?.ToString() ?? "multiple accepted candidates were rejected");
        OcgForgeLogicalModelInputV1 logical = result.Value!;
        Require(logical.CandidateFeatures.Count == 3 &&
                logical.CandidateRouting.Count == 3 &&
                logical.CandidateFeatures[0].Choice?.ResponseIndex == 0 &&
                logical.CandidateFeatures[1].Choice?.ResponseIndex == 1 &&
                logical.CandidateFeatures[2].Choice?.ResponseIndex == 2 &&
                logical.CandidateRouting[0].PublicActionKey == decision.Candidates[0].PublicActionKey &&
                logical.CandidateRouting[1].PublicActionKey == decision.Candidates[1].PublicActionKey &&
                logical.CandidateRouting[2].PublicActionKey == decision.Candidates[2].PublicActionKey,
            "candidate N-to-N order or routing alignment changed");

        OcgForgePublicDecisionContextV1 equivalent =
            CreateAcceptedDecision(frame, New<FlatPromptOptionPublicContextV1>((byte)0), new[]
            {
                New<FlatOptionPublicCandidateDescriptorV1>("other.a", 0, 7UL),
                New<FlatOptionPublicCandidateDescriptorV1>("other.b", 1, 7UL),
                New<FlatOptionPublicCandidateDescriptorV1>("other.c", 2, 9UL)
            });
        OcgForgeLogicalModelInputResultV1 equivalentResult =
            OcgForgeLogicalModelInputBridgeV1.TryCreate(AcceptedBundle(), equivalent);
        Require(equivalentResult.IsSuccess && equivalentResult.Value is not null &&
                logical.CanonicalBytes.SequenceEqual(equivalentResult.Value.CanonicalBytes),
            "Ignis-local candidate keys affected logical model identity");
    }

    private static void TestOptionalPresenceAndHistoricalReferences()
    {
        PerspectiveSafeFrameV1 absentFrame = CreateFrame(turnPlayer: null);
        PerspectiveSafeFrameV1 presentFrame = CreateFrame(turnPlayer: 0);
        OcgForgePublicDecisionContextV1 absentDecision =
            CreateAcceptedDecision(absentFrame, CreateYesNoContext(), new[]
            {
                New<FlatYesNoPublicCandidateDescriptorV1>("absent", FlatPromptChoiceKindV1.No)
            });
        OcgForgePublicDecisionContextV1 presentDecision =
            CreateAcceptedDecision(presentFrame, CreateYesNoContext(), new[]
            {
                New<FlatYesNoPublicCandidateDescriptorV1>("present", FlatPromptChoiceKindV1.No)
            });
        OcgForgeLogicalModelInputV1 absent = RequireLogical(absentDecision);
        OcgForgeLogicalModelInputV1 present = RequireLogical(presentDecision);

        Require(absent.PublicSafeState.Globals.TurnPlayer is null &&
                present.PublicSafeState.Globals.TurnPlayer == 0 &&
                !absent.CanonicalBytes.SequenceEqual(present.CanonicalBytes),
            "ABSENT and PRESENT(0) were collapsed in the logical codec");
        OcgForgeEncodedModelInputV1 absentEncoded =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(
                absent,
                OcgForgeCardVocabularyV1.TryCreate(new uint[] { 1001, 2002, 3003 }).Value!)
                .Value!;
        OcgForgeEncodedModelInputV1 presentEncoded =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(
                present,
                OcgForgeCardVocabularyV1.TryCreate(new uint[] { 1001, 2002, 3003 }).Value!)
                .Value!;
        Require(absentEncoded.Globals.TurnPlayer is null &&
                presentEncoded.Globals.TurnPlayer == 0 &&
                !absentEncoded.CanonicalBytes.SequenceEqual(presentEncoded.CanonicalBytes),
            "ABSENT and PRESENT(0) were collapsed in the encoded codec");
        Require(absent.PublicSafeState.VisibleEvents[0].Entity is { } eventEntity &&
                eventEntity.Locator.PublicLocatorOrdinal < absent.PublicLocatorTable.Count,
            "historical reference did not use the shared locator table");
        Require(absent.PublicSafeState.Relationships[0].Source.CurrentEntityOrdinal is not null &&
                absent.PublicSafeState.Relationships[0].Source.CurrentEntityOrdinal == 1,
            "current relationship reference did not resolve to the entity ordinal");
    }

    private static void TestContinuationSubmissionMetadata()
    {
        PerspectiveSafeFrameV1 frame = CreateFrame();
        PublicSemanticLocatorV1 source = Locator("p0:MONSTER_ZONE:0");
        FlatPromptCardSelectionPublicContextV1 context =
            New<FlatPromptCardSelectionPublicContextV1>((byte)0, 1U, 2U, false);
        OcgForgePublicDecisionContextV1 continuation =
            CreateAcceptedDecision(frame, context, new[]
            {
                New<FlatPromptCardSelectionLocatorCandidateV1>(
                    "local.pick",
                    0,
                    source)
            });
        OcgForgeLogicalModelInputV1 pick = RequireLogical(continuation);
        Require(pick.CandidateFeatures[0].ContinuationOperation == "pick" &&
                !pick.CandidateFeatures[0].SubmitsEngineResponse,
            "accepted intermediate continuation was marked terminal");

        OcgForgePublicDecisionContextV1 finish =
            CreateAcceptedDecision(frame, context, new[]
            {
                New<FlatPromptFinishPublicCandidateV1>("local.finish")
            });
        OcgForgeLogicalModelInputV1 terminal = RequireLogical(finish);
        Require(terminal.CandidateFeatures[0].ContinuationOperation == "finish" &&
                terminal.CandidateFeatures[0].SubmitsEngineResponse,
            "accepted terminal continuation was marked intermediate");
    }

    private static void TestMissingKnownPasscodeFailsClosed()
    {
        OcgForgeLogicalModelInputV1 logical = RequireLogical(
            CreateAcceptedDecision(CreateFrame(), CreateYesNoContext(), new[]
            {
                New<FlatYesNoPublicCandidateDescriptorV1>("missing-vocabulary", FlatPromptChoiceKindV1.No)
            }));
        OcgForgeCardVocabularyResultV1 vocabulary =
            OcgForgeCardVocabularyV1.TryCreate(new uint[] { 2002, 3003 });
        Require(vocabulary.IsSuccess && vocabulary.Value is not null,
            "reduced test vocabulary was rejected");
        OcgForgeEncodedModelInputResultV1 result =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(logical, vocabulary.Value);
        Require(!result.IsSuccess && result.Value is null &&
                result.Error?.Code ==
                    OcgForgeEncodedModelInputErrorCodeV1.UnknownPublicPasscode,
            "known passcode absent from vocabulary was silently redacted");
    }

    private static void TestDetachedAndMalformedInputsFailClosed()
    {
        OcgForgeLogicalModelInputV1 logical = RequireLogical(
            CreateAcceptedDecision(CreateFrame(), CreateYesNoContext(), new[]
            {
                New<FlatYesNoPublicCandidateDescriptorV1>("detached", FlatPromptChoiceKindV1.No)
            }));
        OcgForgeCardVocabularyResultV1 vocabulary =
            OcgForgeCardVocabularyV1.TryCreate(new uint[] { 1001, 2002, 3003 });
        Require(vocabulary.IsSuccess && vocabulary.Value is not null,
            "detachment test vocabulary was rejected");
        OcgForgeEncodedModelInputResultV1 encodedResult =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(logical, vocabulary.Value);
        Require(encodedResult.IsSuccess && encodedResult.Value is not null,
            "detachment fixture did not encode");

        OcgForgeCardVocabularyV1 otherVocabulary =
            OcgForgeCardVocabularyV1.TryCreate(new uint[] { 1001, 2002, 4004 }).Value!;
        OcgForgeModelInputIdentityResultV1 detached =
            OcgForgeModelInputIdentityV1.TryCreate(
                logical,
                encodedResult.Value,
                otherVocabulary);
        Require(!detached.IsSuccess && detached.Identity is null,
            "detached vocabulary was accepted by model identity");

        OcgForgeLogicalModelInputV1 malformed = New<OcgForgeLogicalModelInputV1>(
            OcgForgeLogicalModelInputV1.SchemaId,
            new string('0', 64),
            null,
            (byte)0,
            0UL,
            null,
            null,
            Array.Empty<OcgForgeLogicalPublicLocatorV1>(),
            Array.Empty<OcgForgeLogicalPublicLocatorV1>(),
            logical.PublicSafeState,
            Array.Empty<OcgForgeLogicalCandidateRoutingV1>(),
            Array.Empty<OcgForgeLogicalCandidateV1>());
        OcgForgeEncodedModelInputResultV1 malformedResult =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(malformed, vocabulary.Value);
        Require(!malformedResult.IsSuccess && malformedResult.Value is null &&
                malformedResult.Error?.Code ==
                    OcgForgeEncodedModelInputErrorCodeV1.InvalidLogicalModelInput,
            "malformed logical input was not rejected atomically");
    }

    private static void TestPairedPublicWorldsAndFreshProcessValues()
    {
        OcgForgeLogicalModelInputV1 first = RequireLogical(
            CreateAcceptedDecision(CreateFrame(), CreateYesNoContext(), new[]
            {
                New<FlatYesNoPublicCandidateDescriptorV1>("world-a", FlatPromptChoiceKindV1.Yes)
            }));
        OcgForgeLogicalModelInputV1 second = RequireLogical(
            CreateAcceptedDecision(CreateFrame(), CreateYesNoContext(), new[]
            {
                New<FlatYesNoPublicCandidateDescriptorV1>("world-b", FlatPromptChoiceKindV1.Yes)
            }));
        OcgForgeCardVocabularyV1 vocabulary =
            OcgForgeCardVocabularyV1.TryCreate(new uint[] { 1001, 2002, 3003 }).Value!;
        OcgForgeEncodedModelInputV1 firstEncoded =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(first, vocabulary).Value!;
        OcgForgeEncodedModelInputV1 secondEncoded =
            OcgForgeEncodedModelInputBridgeV1.TryCreate(second, vocabulary).Value!;
        string firstIdentity = OcgForgeModelInputIdentityV1.Create(first, firstEncoded, vocabulary);
        string secondIdentity = OcgForgeModelInputIdentityV1.Create(second, secondEncoded, vocabulary);
        Require(first.CanonicalBytes.SequenceEqual(second.CanonicalBytes) &&
                firstEncoded.CanonicalBytes.SequenceEqual(secondEncoded.CanonicalBytes) &&
                firstIdentity == secondIdentity,
            "equal public paired worlds did not produce equal I6E values");
        Console.WriteLine($"I6E_MODEL_INPUT_IDENTITY={firstIdentity}");
        Console.WriteLine($"I6E_LOGICAL_LENGTH={first.CanonicalBytes.Length}");
        Console.WriteLine($"I6E_ENCODED_LENGTH={firstEncoded.CanonicalBytes.Length}");
    }

    private static OcgForgeModelContractBundleV1 AcceptedBundle()
    {
        OcgForgeModelContractBundlePreflightResultV1 result =
            OcgForgeModelContractBundleV1.TryAccept(I6BBundlePreflightTests.CreateManifest());
        Require(result.IsSuccess && result.Bundle is not null,
            result.Error?.ToString() ?? "accepted I6B bundle was rejected");
        return result.Bundle!;
    }

    private static OcgForgeLogicalModelInputV1 RequireLogical(
        OcgForgePublicDecisionContextV1 decision)
    {
        OcgForgeLogicalModelInputResultV1 result =
            OcgForgeLogicalModelInputBridgeV1.TryCreate(AcceptedBundle(), decision);
        Require(result.IsSuccess && result.Value is not null,
            result.Error?.ToString() ?? "logical input was rejected");
        return result.Value!;
    }

    private static OcgForgePublicDecisionContextV1 CreateAcceptedDecision(
        PerspectiveSafeFrameV1 frame,
        FlatPromptPublicContextV1 context,
        IReadOnlyList<FlatPublicCandidateDescriptorV1> candidates)
    {
        FlatPromptProjectionResultV1 projection = New<FlatPromptProjectionResultV1>(
            true,
            FlatPromptErrorCodeV1.None,
            context,
            candidates);
        OcgForgeAcceptedDecisionBoundaryProducerV1 producer = new();
        Require(producer.TryAccept(
                frame,
                projection,
                out OcgForgeAcceptedDecisionBoundaryV1? accepted,
                out OcgForgeAcceptedDecisionBoundaryProducerErrorV1? error) &&
            accepted is not null,
            error?.ToString() ?? "accepted decision boundary was rejected");
        OcgForgePublicDecisionContextResultV1 result =
            OcgForgePublicCandidateBridgeV1.TryCreate(accepted);
        Require(result.IsSuccess && result.Context is not null,
            result.Error?.ToString() ?? "I6D public decision context was rejected");
        return result.Context!;
    }

    private static FlatPromptPublicContextV1 CreateChainContext() =>
        New<FlatPromptChainPublicContextV1>((byte)0, (byte)0, false, 0U, 0U);

    private static FlatPromptPublicContextV1 CreateYesNoContext() =>
        New<FlatPromptYesNoPublicContextV1>((byte)0, 42UL);

    private static PerspectiveSafeFrameV1 CreateMinimalFrame()
    {
        PerspectiveSafeFrameSourceResultV1 result =
            PerspectiveSafePublicFrameSourceV1.TryCreate(
                new PerspectiveSafeFrameSourceInputV1(
                    new PerspectiveSafeGlobalsV1(
                        duelFlags: 0,
                        lifePoints: new uint[] { 8000, 8000 },
                        playerToAct: null,
                        turnPlayer: null,
                        turnCount: null,
                        phase: null,
                        chainLength: 0,
                        winner: null,
                        winReason: null,
                        terminal: false),
                    Array.Empty<PerspectiveSafeZoneV1>(),
                    Array.Empty<PerspectiveSafeEntityV1>(),
                    Array.Empty<PerspectiveSafeRelationshipV1>(),
                    new PerspectiveSafeChainStateV1(
                        0,
                        Array.Empty<PerspectiveSafeChainLinkV1>()),
                    Array.Empty<PerspectiveSafeVisibleEventV1>(),
                    new PerspectiveSafeMatchContextV1(
                        0,
                        0,
                        new PerspectiveSafeKnowledgeV1(true, false),
                        new PerspectiveSafeDeckV1(false),
                        new PerspectiveSafeDeckV1(false))));
        Require(result.IsSuccess && result.Frame is not null,
            result.Error?.ToString() ?? "minimal native KAT frame was rejected");
        return result.Frame!;
    }

    private static PerspectiveSafeFrameV1 CreateFrame(byte? turnPlayer = 0)
    {
        PerspectiveSafeCardPropertiesV1 printedMonster = new(
            type: 0x401,
            attribute: 0x20,
            race: 0x1,
            attack: 2500,
            defense: 2000,
            baseAttack: 2500,
            baseDefense: 2000,
            level: 8,
            linkRating: 2,
            linkMarkers: new[]
            {
                PerspectiveSafeLinkMarkerV1.Bottom,
                PerspectiveSafeLinkMarkerV1.Right
            });
        PerspectiveSafeCardPropertiesV1 currentMonster = new(
            type: 0x401,
            attribute: 0x20,
            race: 0x1,
            attack: 2700,
            defense: 2100,
            baseAttack: 2500,
            baseDefense: 2000,
            level: 8,
            linkRating: 2,
            linkMarkers: new[]
            {
                PerspectiveSafeLinkMarkerV1.Bottom,
                PerspectiveSafeLinkMarkerV1.Right
            },
            statusFlags: 8,
            counters: new[] { new PerspectiveSafeCounterV1(7, 3) });
        PerspectiveSafeCardPropertiesV1 printedHand = new(
            type: 0x2,
            attribute: 0x10,
            race: 0x2,
            level: 4);

        PerspectiveSafeEntityV1[] entities =
        {
            new(
                "p0:HAND:public:2002:0",
                true,
                2002,
                0,
                0,
                PerspectiveSafeSemanticZoneV1.Hand,
                0,
                null,
                PerspectiveSafePositionV1.FaceUpAttack,
                true,
                false,
                printedHand,
                null),
            new(
                "p0:MONSTER_ZONE:0",
                true,
                1001,
                0,
                0,
                PerspectiveSafeSemanticZoneV1.MonsterZone,
                0,
                null,
                PerspectiveSafePositionV1.FaceUpAttack,
                true,
                false,
                printedMonster,
                currentMonster),
            new(
                "p1:SPELL_TRAP_ZONE:0",
                false,
                null,
                1,
                1,
                PerspectiveSafeSemanticZoneV1.SpellTrapZone,
                0,
                null,
                PerspectiveSafePositionV1.FaceDownDefense,
                false,
                true)
        };

        PerspectiveSafeFrameSourceResultV1 result =
            PerspectiveSafePublicFrameSourceV1.TryCreate(
                new PerspectiveSafeFrameSourceInputV1(
                    new PerspectiveSafeGlobalsV1(
                        duelFlags: 0x1122334455667788UL,
                        lifePoints: new uint[] { 8000, 7000 },
                        playerToAct: null,
                        turnPlayer: turnPlayer,
                        turnCount: 0,
                        phase: 0,
                        chainLength: 1),
                    new[]
                    {
                        new PerspectiveSafeZoneV1(0, PerspectiveSafeSemanticZoneV1.MainDeck, 40, 0, 40, false),
                        new PerspectiveSafeZoneV1(0, PerspectiveSafeSemanticZoneV1.MonsterZone, 1, 1, 0, true),
                        new PerspectiveSafeZoneV1(1, PerspectiveSafeSemanticZoneV1.MainDeck, 40, 0, 40, false),
                        new PerspectiveSafeZoneV1(1, PerspectiveSafeSemanticZoneV1.SpellTrapZone, 1, 0, 1, false)
                    },
                    entities,
                    new[]
                    {
                        new PerspectiveSafeRelationshipV1(
                            PerspectiveSafeRelationshipKindV1.Target,
                            "p0:MONSTER_ZONE:0",
                            "p0:HAND:public:2002:0")
                    },
                    new PerspectiveSafeChainStateV1(
                        1,
                        new[]
                        {
                            new PerspectiveSafeChainLinkV1(
                                0,
                                0,
                                "p0:MONSTER_ZONE:0",
                                PerspectiveSafeSemanticZoneV1.MonsterZone,
                                0x1020304050607080UL,
                                new[] { "p0:HAND:public:2002:0" })
                        }),
                    new[]
                    {
                        new PerspectiveSafeVisibleEventV1(
                            1,
                            PerspectiveSafeVisibleEventKindV1.CardMoved,
                            0,
                            "p0:MONSTER_ZONE:0",
                            1001,
                            PerspectiveSafeSemanticZoneV1.Hand,
                            PerspectiveSafeSemanticZoneV1.MonsterZone,
                            1,
                            -500,
                            7,
                            0,
                            null,
                            null,
                            0x1020304050607080UL,
                            new[] { "p1:SPELL_TRAP_ZONE:0" }),
                        new PerspectiveSafeVisibleEventV1(
                            2,
                            PerspectiveSafeVisibleEventKindV1.CounterChanged,
                            0,
                            "p0:MONSTER_ZONE:0",
                            null,
                            null,
                            null,
                            3,
                            null,
                            7,
                            0,
                            null,
                            null,
                            null,
                            Array.Empty<string>())
                    },
                    new PerspectiveSafeMatchContextV1(
                        0,
                        0x1122334455667788UL,
                        new PerspectiveSafeKnowledgeV1(true, false),
                        new PerspectiveSafeDeckV1(true, new uint[] { 1001, 2002 }, new uint[] { 3003 }),
                        new PerspectiveSafeDeckV1(false))));
        Require(result.IsSuccess && result.Frame is not null,
            result.Error?.ToString() ?? "public I6E frame was rejected");
        return result.Frame!;
    }

    private static PublicSemanticLocatorV1 Locator(string text)
    {
        Require(PublicSemanticLocatorV1.TryParse(text, out PublicSemanticLocatorV1? value) &&
                value is not null,
            $"invalid test locator {text}");
        return value!;
    }

    private static T New<T>(params object?[] arguments)
        where T : class
    {
        object? value = Activator.CreateInstance(
            typeof(T),
            BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic,
            binder: null,
            args: arguments,
            culture: CultureInfo.InvariantCulture);
        return (T)(value ?? throw new InvalidOperationException(
            $"Could not construct {typeof(T).Name}."));
    }

    private static void Require(bool condition, string message)
    {
        if (!condition)
        {
            throw new InvalidOperationException(message);
        }
    }
}
